### ISSUE TITLE
User creation trough the API

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamPythonAPI#2]
Would it be possible to create an account in slipstream programmatically ? With the API or any other entry point ?

Ticket moved from https://github.com/SixSq/SlipStreamClientClara/issues/5

**Comment by schaubl** [comment]
@st If logged as a privileged user yes

**Comment by bryan-brancotte** [comment]
Can we add this possibility into the API ?

User stories :
- As a privileged user i can create new account for user with at most as privileg as I have
- As a privileged user i can change the password of a less-privileged account without knowning its current password
