### ISSUE TITLE
Get list of VM flavor for given cloud

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStreamPythonAPI#25]
I am aware of https://nuv.la/api/service-offer but it does not return me an xml when I [ask for (?media=xml)](https://nuv.la/api/service-offer?media=xml). I also don't know the accuracy and completeness of the information returned. 
As soon as I have a way to get the flavor in xml, I will implement the function and make a pull request.

**Comment by loomis** [comment]
For information, the "new" resources under "https://nuv.la/api" will only return JSON.  There are no plans to provide an XML representation for those resources.

**Comment by bryan-brancotte** [comment]
Ok, I can work with the json. Are you ok with the idea of having a function in the API using this json source to return the flavors ? In case you are, I can propose you one by a pull request.

**Comment by loomis** [comment]
@schaubl is better placed to decide what should/shouldn't be in the API.  However, in general it is probably better to search for offers that meet the requirements of a component/application than trying to choose the flavors directly.

**Comment by bryan-brancotte** [comment]
I agree that it would be cleaner to specify the number of core/ram/storage a user wants instead of the flavor. I guess that I can specify it in `raw_params` of function `deploy` in the API but I have not found yet a doc listing what can be specified in it, and how. Could you please indicate me where I can find this information?

User stories:
As an api user, I can specify the minimum number of core I need for each component of an application I am starting
As an api user, I don't have to specify the minimum number of core I need for each component of an application I am starting

**Comment by bryan-brancotte** [comment]
spec and/or flavor can be specified when calling depliy of the API
