### ISSUE TITLE
User updates trough the API

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStreamPythonAPI#28]
Hi SixSq,
I tried to implement it by my self, but I ends up on strange behavior. Let's say I want to change the organization and lastName of user 'lemigns_DMM9', I tried:
- use HTTP PATCH verb on url '/user/lemigns_DMM9' with xml content `<?xml version='1.0' encoding='UTF-8'?>
<user lastName="D5EDQ" name="lemigns_DMM9" organization="new !" state="ACTIVE" />` but i get 'slipstream.api.api.SlipStreamError: First name cannot be empty.'
- use HTTP PATCH verb with all informations (with new value) and a duplicate appears in /user
![image](https://cloud.githubusercontent.com/assets/11556772/21016245/39dba0da-bd65-11e6-949a-6d405a0914fb.png) 
note that whether I click on first or second user I logicaly  ends on the second one
- use HTTP PUT verb with all informations and also get a duplicate

Note also that when I then try to update another user TOTO, the duplicate of lemigns_DMM9 disapear and a duplicates of TOTO appears.

I'm using slipstream 3.14 started from nuv.la workspace

**Comment by bryan-brancotte** [comment]
Hi SixSq
Is there any update ?
Best regards

**Comment by schaubl** [comment]
Hi @bryan-brancotte,
I will work on this today.
Regards

**Comment by bryan-brancotte** [comment]
Thanks !
With PUT or PATCH verb ?

**Comment by schaubl** [comment]
PATCH is not implemented.
We have to use PUT with the full XML.
A PR will come today.

**Comment by schaubl** [comment]
The code is ready but there is an issue server-side which prevent it to work.
So I will wait until the fix is released before pushing the code.

**Comment by bryan-brancotte** [comment]
Hi @schaubl 
Is the server-side bug fixed ? I look forward to see the code merged, and ready to be used !
Regards

**Comment by schaubl** [comment]
Hi @bryan-brancotte,

Bugs server-side has been fixed and included in the last release.

The `update_user()` function is now part of master.

[Nuvla](https://nuv.la) will be updated today so once updated you will be able to use the new function to update users on Nuvla.

Sorry for the delay.
Regards
