### ISSUE TITLE
Specification/flavor not taken into account when calling deploy

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStreamPythonAPI#39]
Hi all,

_Sorry for duplication if it is the case, I can not put an hand on any older issue about it_ 

With the API we can either specify the spec, or the flavor. I did it with run https://nuv.la/run/e8d46f19-4858-4b4b-af9c-e2692a6f0d4e
![image](https://cloud.githubusercontent.com/assets/11556772/26717446/ba28b960-477d-11e7-861d-d8df0a5c5d92.png)

The thing is that the VM created only have 1 core and 2GB of ram while we asked for 8vcpu and 16ram.

Am I doing it wrong ? Does the function not available yet ?

Best regards

**Comment by 0xbase12** [comment]
Hi Bryan,

Specifying a Flavor during the launch of a run is not yet implemented on Nuvla. Actually, cloud connector parameters  are extracted from the image and not from the run.

Nevertheless, this was implemented last week. Values for cloud connector parameters are taken by priority from the run. Next monday, an update is planned for Nuvla.
After the update of Nuvla, the flavor specified via the API should be taken into account at launch time of your VM.

Best regards.

**Comment by bryan-brancotte** [comment]
Hi Khaled,

Great news ! I can't wait to test it !

Bryan

**Comment by 0xbase12** [comment]
@bryan-brancotte oups forgot that next monday is holiday in Geneva, so it will be updated next tuesday

**Comment by 0xbase12** [comment]
@bryan-brancotte Have you tested it?

**Comment by bryan-brancotte** [comment]
Hi @0xbase12 
Since the update of Tuesday 6th we (IFB) are not able to start appliance on any cloud (http://support.sixsq.com/support/tickets/1690).
![image](https://user-images.githubusercontent.com/11556772/27028305-b594326e-4f64-11e7-8d0b-4de6cbc63a70.png)
Note that also Erik (TUB) has the same problem.

But I will test it as soon as I can !

**Comment by 0xbase12** [comment]
Hello, we got an issue during the release which prevent all run image to start. The issue was noticed and resolved few hours after the release.

Thanks a lot.  It will be great to have your test results when you have some time to do them.

**Comment by bryan-brancotte** [comment]
After talking to colleagues, only one of us can start appliance. Switching to (http://support.sixsq.com/support/tickets/1690) to give names and details.

**Comment by bryan-brancotte** [comment]
Running application is OK, but running component is KO, I updated the issue (http://support.sixsq.com/support/tickets/1690)

**Comment by bryan-brancotte** [comment]
(the issue has been fixed)
We are able to leverage your dev, we now can specify the flavor of a component at runtime.
Thanks
