### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamPythonAPI#5]
As a user of the Python API, I should be able to:
- list all available commands
- know for each which arguments are needed

**Comment by schaubl** [comment]
@st : This has been done.

We can get the full documentation by typing:
_Python shell/code_
```python
from slipstream.api import Api
help(Api)
```
_Shell_
```bash
pydoc slipstream.api.Api
```

Or for a specific function:
_Python shell/code_
```python
from slipstream.api import Api
help(Api.deploy)
```
_Shell_
```bash
pydoc slipstream.api.Api.deploy
```

Or to get only the docstring:
_Python shell/code_
```python
from slipstream.api import Api
print Api.deploy.__doc__
```

Currently there is no HTML version of the documentation, only docstring inside the code but the documentation can be generated by the user. 
To run a local webserver with the documentation you can run:
```shell
pydoc -p 8080 slipstream.api.Api
```

**Comment by konstan** [comment]
@schaubl Can this issue be closed?
